### ISSUE TITLE
https://pentacle.tools/mint-nft links to phantom wallet docs that don't work anymore

### ISSUE THREAD

**Issue by SvenDowideit** [penta-fun/pentacle.tools#15]
https://docs.phantom.app/integrating/tokens/non-fungible-tokens is now a 404..

idk what that used to go to, so i'm not sure where it should point now

**Comment by 21e8** [comment]
hey @SvenDowideit thanks for bringing this up, I updated this with the correct Metaplex link

**Comment by SvenDowideit** [comment]
awesome! thanks :)

(closing as FIXED)
